name: PR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-go:
    name: "Lint Go"
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Force git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: --verbose
